export const CREATE_ELEMENT_REQUEST = "CREATE_ELEMENT_REQUEST";
export const CREATE_ELEMENT_SUCCESS = "CREATE_ELEMENT_SUCCESS";
export const CREATE_ELEMENT_FAILURE = "CREATE_ELEMENT_FAILURE";

export const GET_ELEMENTS_REQUEST = "GET_ELEMENT_REQUEST";
export const GET_ELEMENTS_SUCCESS = "GET_ELEMENT_SUCCESS";
export const GET_ELEMENTS_FAILURE = "GET_ELEMENT_FAILURE";

export const UPDATE_ELEMENT_REQUEST = "UPDATE_ELEMENT_REQUEST";
export const UPDATE_ELEMENT_SUCCESS = "UPDATE_ELEMENT_SUCCESS";
export const UPDATE_ELEMENT_FAILURE = "UPDATE_ELEMENT_FAILURE";

export const DELETE_ELEMENT_REQUEST = "DELETE_ELEMENT_REQUEST";
export const DELETE_ELEMENT_SUCCESS = "DELETE_ELEMENT_SUCCESS";
export const DELETE_ELEMENT_FAILURE = "DELETE_ELEMENT_FAILURE";
