export const ADD_ITEM_TO_INGREDIENTTABLE_REQUEST =
  "ADD_ITEM_TO_INGREDIENTTABLE_REQUEST";
export const ADD_ITEM_TO_INGREDIENTTABLE_SUCCESS =
  "ADD_ITEM_TO_INGREDIENTTABLE_SUCCESS";
export const ADD_ITEM_TO_INGREDIENTTABLE_FAILURE =
  "ADD_ITEM_TO_INGREDIENTTABLE_FAILURE";

export const GET_INGREDIENTTABLE_REQUEST = "GET_INGREDIENTTABLE_REQUEST";
export const GET_INGREDIENTTABLE_SUCCESS = "GET_INGREDIENTTABLE_SUCCESS";
export const GET_INGREDIENTTABLE_FAILURE = "GET_INGREDIENTTABLE_FAILURE";

export const REMOVE_INGREDIENTTABLE_ITEM_REQUEST =
  "REMOVE_INGREDIENTTABLE_ITEM_REQUEST";
export const REMOVE_INGREDIENTTABLE_ITEM_SUCCESS =
  "REMOVE_INGREDIENTTABLE_ITEM_SUCCESS";
export const REMOVE_INGREDIENTTABLE_ITEM_FAILURE =
  "REMOVE_INGREDIENTTABLE_ITEM_FAILURE";

export const UPDATE_INGREDIENTTABLE_ITEM_REQUEST =
  "UPDATE_INGREDIENTTABLE_ITEM_REQUEST";
export const UPDATE_INGREDIENTTABLE_ITEM_SUCCESS =
  "UPDATE_INGREDIENTTABLE_ITEM_SUCCESS";
export const UPDATE_INGREDIENTTABLE_ITEM_FAILURE =
  "UPDATE_INGREDIENTTABLE_ITEM_FAILURE";
